/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as DcRouteImport } from './routes/dc'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AccountDeleteRouteImport } from './routes/account_.delete'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDeskCrawlerRouteImport } from './routes/app/desk-crawler'
import { Route as DeskCrawlerUnsubscribeRouteImport } from './routes/desk-crawler/unsubscribe'
import { Route as DeskCrawlerWaitingListRouteImport } from './routes/desk-crawler/waiting-list'
import { Route as DevDeskCrawlerRouteImport } from './routes/dev/desk-crawler'
import { Route as DevOgRouteImport } from './routes/dev/og'
import { Route as GamesDeskCrawlerRouteImport } from './routes/games/desk-crawler'
import { Route as HelpDeskCrawlerRouteImport } from './routes/help/desk-crawler'
import { Route as AppDeskCrawlerIndexRouteImport } from './routes/app/desk-crawler/index'
import { Route as AppDeskCrawlerInventoryRouteImport } from './routes/app/desk-crawler/inventory'
import { Route as AppDeskCrawlerLeaderboardRouteImport } from './routes/app/desk-crawler/leaderboard'
import { Route as AppDeskCrawlerSettingsRouteImport } from './routes/app/desk-crawler/settings'
import { Route as DeskCrawlerHeroesAliasRouteImport } from './routes/desk-crawler/heroes.$alias'
import { Route as ConnectTrmnlDeskCrawlerInstallRouteImport } from './routes/connect/trmnl/desk-crawler/install'
import { Route as ConnectTrmnlDeskCrawlerManageRouteImport } from './routes/connect/trmnl/desk-crawler/manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DcRoute = DcRouteImport.update({
  id: '/dc',
  path: '/dc',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeleteRoute = AccountDeleteRouteImport.update({
  id: '/account_/delete',
  path: '/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeskCrawlerRoute = AppDeskCrawlerRouteImport.update({
  id: '/desk-crawler',
  path: '/desk-crawler',
  getParentRoute: () => AppRoute,
} as any)
const DeskCrawlerUnsubscribeRoute = DeskCrawlerUnsubscribeRouteImport.update({
  id: '/desk-crawler/unsubscribe',
  path: '/desk-crawler/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskCrawlerWaitingListRoute = DeskCrawlerWaitingListRouteImport.update({
  id: '/desk-crawler/waiting-list',
  path: '/desk-crawler/waiting-list',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDeskCrawlerRoute = DevDeskCrawlerRouteImport.update({
  id: '/dev/desk-crawler',
  path: '/dev/desk-crawler',
  getParentRoute: () => rootRouteImport,
} as any)
const DevOgRoute = DevOgRouteImport.update({
  id: '/dev/og',
  path: '/dev/og',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDeskCrawlerRoute = GamesDeskCrawlerRouteImport.update({
  id: '/games/desk-crawler',
  path: '/games/desk-crawler',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpDeskCrawlerRoute = HelpDeskCrawlerRouteImport.update({
  id: '/help/desk-crawler',
  path: '/help/desk-crawler',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeskCrawlerIndexRoute = AppDeskCrawlerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDeskCrawlerRoute,
} as any)
const AppDeskCrawlerInventoryRoute = AppDeskCrawlerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppDeskCrawlerRoute,
} as any)
const AppDeskCrawlerLeaderboardRoute =
  AppDeskCrawlerLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AppDeskCrawlerRoute,
  } as any)
const AppDeskCrawlerSettingsRoute = AppDeskCrawlerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDeskCrawlerRoute,
} as any)
const DeskCrawlerHeroesAliasRoute = DeskCrawlerHeroesAliasRouteImport.update({
  id: '/desk-crawler/heroes/$alias',
  path: '/desk-crawler/heroes/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectTrmnlDeskCrawlerInstallRoute =
  ConnectTrmnlDeskCrawlerInstallRouteImport.update({
    id: '/connect/trmnl/desk-crawler/install',
    path: '/connect/trmnl/desk-crawler/install',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConnectTrmnlDeskCrawlerManageRoute =
  ConnectTrmnlDeskCrawlerManageRouteImport.update({
    id: '/connect/trmnl/desk-crawler/manage',
    path: '/connect/trmnl/desk-crawler/manage',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/dc': typeof DcRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/app/desk-crawler': typeof AppDeskCrawlerRouteWithChildren
  '/desk-crawler/unsubscribe': typeof DeskCrawlerUnsubscribeRoute
  '/desk-crawler/waiting-list': typeof DeskCrawlerWaitingListRoute
  '/dev/desk-crawler': typeof DevDeskCrawlerRoute
  '/dev/og': typeof DevOgRoute
  '/games/desk-crawler': typeof GamesDeskCrawlerRoute
  '/help/desk-crawler': typeof HelpDeskCrawlerRoute
  '/app/': typeof AppIndexRoute
  '/app/desk-crawler/inventory': typeof AppDeskCrawlerInventoryRoute
  '/app/desk-crawler/leaderboard': typeof AppDeskCrawlerLeaderboardRoute
  '/app/desk-crawler/settings': typeof AppDeskCrawlerSettingsRoute
  '/desk-crawler/heroes/$alias': typeof DeskCrawlerHeroesAliasRoute
  '/app/desk-crawler/': typeof AppDeskCrawlerIndexRoute
  '/connect/trmnl/desk-crawler/install': typeof ConnectTrmnlDeskCrawlerInstallRoute
  '/connect/trmnl/desk-crawler/manage': typeof ConnectTrmnlDeskCrawlerManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dc': typeof DcRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account/delete': typeof AccountDeleteRoute
  '/desk-crawler/unsubscribe': typeof DeskCrawlerUnsubscribeRoute
  '/desk-crawler/waiting-list': typeof DeskCrawlerWaitingListRoute
  '/dev/desk-crawler': typeof DevDeskCrawlerRoute
  '/dev/og': typeof DevOgRoute
  '/games/desk-crawler': typeof GamesDeskCrawlerRoute
  '/help/desk-crawler': typeof HelpDeskCrawlerRoute
  '/app': typeof AppIndexRoute
  '/app/desk-crawler/inventory': typeof AppDeskCrawlerInventoryRoute
  '/app/desk-crawler/leaderboard': typeof AppDeskCrawlerLeaderboardRoute
  '/app/desk-crawler/settings': typeof AppDeskCrawlerSettingsRoute
  '/desk-crawler/heroes/$alias': typeof DeskCrawlerHeroesAliasRoute
  '/app/desk-crawler': typeof AppDeskCrawlerIndexRoute
  '/connect/trmnl/desk-crawler/install': typeof ConnectTrmnlDeskCrawlerInstallRoute
  '/connect/trmnl/desk-crawler/manage': typeof ConnectTrmnlDeskCrawlerManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/dc': typeof DcRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/account_/delete': typeof AccountDeleteRoute
  '/app/desk-crawler': typeof AppDeskCrawlerRouteWithChildren
  '/desk-crawler/unsubscribe': typeof DeskCrawlerUnsubscribeRoute
  '/desk-crawler/waiting-list': typeof DeskCrawlerWaitingListRoute
  '/dev/desk-crawler': typeof DevDeskCrawlerRoute
  '/dev/og': typeof DevOgRoute
  '/games/desk-crawler': typeof GamesDeskCrawlerRoute
  '/help/desk-crawler': typeof HelpDeskCrawlerRoute
  '/app/': typeof AppIndexRoute
  '/app/desk-crawler/inventory': typeof AppDeskCrawlerInventoryRoute
  '/app/desk-crawler/leaderboard': typeof AppDeskCrawlerLeaderboardRoute
  '/app/desk-crawler/settings': typeof AppDeskCrawlerSettingsRoute
  '/desk-crawler/heroes/$alias': typeof DeskCrawlerHeroesAliasRoute
  '/app/desk-crawler/': typeof AppDeskCrawlerIndexRoute
  '/connect/trmnl/desk-crawler/install': typeof ConnectTrmnlDeskCrawlerInstallRoute
  '/connect/trmnl/desk-crawler/manage': typeof ConnectTrmnlDeskCrawlerManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/dc'
    | '/feedback'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/account/delete'
    | '/app/desk-crawler'
    | '/desk-crawler/unsubscribe'
    | '/desk-crawler/waiting-list'
    | '/dev/desk-crawler'
    | '/dev/og'
    | '/games/desk-crawler'
    | '/help/desk-crawler'
    | '/app/'
    | '/app/desk-crawler/inventory'
    | '/app/desk-crawler/leaderboard'
    | '/app/desk-crawler/settings'
    | '/desk-crawler/heroes/$alias'
    | '/app/desk-crawler/'
    | '/connect/trmnl/desk-crawler/install'
    | '/connect/trmnl/desk-crawler/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/dc'
    | '/feedback'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/account/delete'
    | '/desk-crawler/unsubscribe'
    | '/desk-crawler/waiting-list'
    | '/dev/desk-crawler'
    | '/dev/og'
    | '/games/desk-crawler'
    | '/help/desk-crawler'
    | '/app'
    | '/app/desk-crawler/inventory'
    | '/app/desk-crawler/leaderboard'
    | '/app/desk-crawler/settings'
    | '/desk-crawler/heroes/$alias'
    | '/app/desk-crawler'
    | '/connect/trmnl/desk-crawler/install'
    | '/connect/trmnl/desk-crawler/manage'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/dc'
    | '/feedback'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/account_/delete'
    | '/app/desk-crawler'
    | '/desk-crawler/unsubscribe'
    | '/desk-crawler/waiting-list'
    | '/dev/desk-crawler'
    | '/dev/og'
    | '/games/desk-crawler'
    | '/help/desk-crawler'
    | '/app/'
    | '/app/desk-crawler/inventory'
    | '/app/desk-crawler/leaderboard'
    | '/app/desk-crawler/settings'
    | '/desk-crawler/heroes/$alias'
    | '/app/desk-crawler/'
    | '/connect/trmnl/desk-crawler/install'
    | '/connect/trmnl/desk-crawler/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  DcRoute: typeof DcRoute
  FeedbackRoute: typeof FeedbackRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AccountDeleteRoute: typeof AccountDeleteRoute
  DeskCrawlerUnsubscribeRoute: typeof DeskCrawlerUnsubscribeRoute
  DeskCrawlerWaitingListRoute: typeof DeskCrawlerWaitingListRoute
  DevDeskCrawlerRoute: typeof DevDeskCrawlerRoute
  DevOgRoute: typeof DevOgRoute
  GamesDeskCrawlerRoute: typeof GamesDeskCrawlerRoute
  HelpDeskCrawlerRoute: typeof HelpDeskCrawlerRoute
  DeskCrawlerHeroesAliasRoute: typeof DeskCrawlerHeroesAliasRoute
  ConnectTrmnlDeskCrawlerInstallRoute: typeof ConnectTrmnlDeskCrawlerInstallRoute
  ConnectTrmnlDeskCrawlerManageRoute: typeof ConnectTrmnlDeskCrawlerManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dc': {
      id: '/dc'
      path: '/dc'
      fullPath: '/dc'
      preLoaderRoute: typeof DcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/delete': {
      id: '/account_/delete'
      path: '/account/delete'
      fullPath: '/account/delete'
      preLoaderRoute: typeof AccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/desk-crawler': {
      id: '/app/desk-crawler'
      path: '/desk-crawler'
      fullPath: '/app/desk-crawler'
      preLoaderRoute: typeof AppDeskCrawlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/desk-crawler/unsubscribe': {
      id: '/desk-crawler/unsubscribe'
      path: '/desk-crawler/unsubscribe'
      fullPath: '/desk-crawler/unsubscribe'
      preLoaderRoute: typeof DeskCrawlerUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk-crawler/waiting-list': {
      id: '/desk-crawler/waiting-list'
      path: '/desk-crawler/waiting-list'
      fullPath: '/desk-crawler/waiting-list'
      preLoaderRoute: typeof DeskCrawlerWaitingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/desk-crawler': {
      id: '/dev/desk-crawler'
      path: '/dev/desk-crawler'
      fullPath: '/dev/desk-crawler'
      preLoaderRoute: typeof DevDeskCrawlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/og': {
      id: '/dev/og'
      path: '/dev/og'
      fullPath: '/dev/og'
      preLoaderRoute: typeof DevOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/desk-crawler': {
      id: '/games/desk-crawler'
      path: '/games/desk-crawler'
      fullPath: '/games/desk-crawler'
      preLoaderRoute: typeof GamesDeskCrawlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/desk-crawler': {
      id: '/help/desk-crawler'
      path: '/help/desk-crawler'
      fullPath: '/help/desk-crawler'
      preLoaderRoute: typeof HelpDeskCrawlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/desk-crawler/': {
      id: '/app/desk-crawler/'
      path: '/'
      fullPath: '/app/desk-crawler/'
      preLoaderRoute: typeof AppDeskCrawlerIndexRouteImport
      parentRoute: typeof AppDeskCrawlerRoute
    }
    '/app/desk-crawler/inventory': {
      id: '/app/desk-crawler/inventory'
      path: '/inventory'
      fullPath: '/app/desk-crawler/inventory'
      preLoaderRoute: typeof AppDeskCrawlerInventoryRouteImport
      parentRoute: typeof AppDeskCrawlerRoute
    }
    '/app/desk-crawler/leaderboard': {
      id: '/app/desk-crawler/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/desk-crawler/leaderboard'
      preLoaderRoute: typeof AppDeskCrawlerLeaderboardRouteImport
      parentRoute: typeof AppDeskCrawlerRoute
    }
    '/app/desk-crawler/settings': {
      id: '/app/desk-crawler/settings'
      path: '/settings'
      fullPath: '/app/desk-crawler/settings'
      preLoaderRoute: typeof AppDeskCrawlerSettingsRouteImport
      parentRoute: typeof AppDeskCrawlerRoute
    }
    '/desk-crawler/heroes/$alias': {
      id: '/desk-crawler/heroes/$alias'
      path: '/desk-crawler/heroes/$alias'
      fullPath: '/desk-crawler/heroes/$alias'
      preLoaderRoute: typeof DeskCrawlerHeroesAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/trmnl/desk-crawler/install': {
      id: '/connect/trmnl/desk-crawler/install'
      path: '/connect/trmnl/desk-crawler/install'
      fullPath: '/connect/trmnl/desk-crawler/install'
      preLoaderRoute: typeof ConnectTrmnlDeskCrawlerInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/trmnl/desk-crawler/manage': {
      id: '/connect/trmnl/desk-crawler/manage'
      path: '/connect/trmnl/desk-crawler/manage'
      fullPath: '/connect/trmnl/desk-crawler/manage'
      preLoaderRoute: typeof ConnectTrmnlDeskCrawlerManageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDeskCrawlerRouteChildren {
  AppDeskCrawlerInventoryRoute: typeof AppDeskCrawlerInventoryRoute
  AppDeskCrawlerLeaderboardRoute: typeof AppDeskCrawlerLeaderboardRoute
  AppDeskCrawlerSettingsRoute: typeof AppDeskCrawlerSettingsRoute
  AppDeskCrawlerIndexRoute: typeof AppDeskCrawlerIndexRoute
}

const AppDeskCrawlerRouteChildren: AppDeskCrawlerRouteChildren = {
  AppDeskCrawlerInventoryRoute: AppDeskCrawlerInventoryRoute,
  AppDeskCrawlerLeaderboardRoute: AppDeskCrawlerLeaderboardRoute,
  AppDeskCrawlerSettingsRoute: AppDeskCrawlerSettingsRoute,
  AppDeskCrawlerIndexRoute: AppDeskCrawlerIndexRoute,
}

const AppDeskCrawlerRouteWithChildren = AppDeskCrawlerRoute._addFileChildren(
  AppDeskCrawlerRouteChildren,
)

interface AppRouteChildren {
  AppDeskCrawlerRoute: typeof AppDeskCrawlerRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDeskCrawlerRoute: AppDeskCrawlerRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  DcRoute: DcRoute,
  FeedbackRoute: FeedbackRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AccountDeleteRoute: AccountDeleteRoute,
  DeskCrawlerUnsubscribeRoute: DeskCrawlerUnsubscribeRoute,
  DeskCrawlerWaitingListRoute: DeskCrawlerWaitingListRoute,
  DevDeskCrawlerRoute: DevDeskCrawlerRoute,
  DevOgRoute: DevOgRoute,
  GamesDeskCrawlerRoute: GamesDeskCrawlerRoute,
  HelpDeskCrawlerRoute: HelpDeskCrawlerRoute,
  DeskCrawlerHeroesAliasRoute: DeskCrawlerHeroesAliasRoute,
  ConnectTrmnlDeskCrawlerInstallRoute: ConnectTrmnlDeskCrawlerInstallRoute,
  ConnectTrmnlDeskCrawlerManageRoute: ConnectTrmnlDeskCrawlerManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
