import { sprite, type Sprite } from './canvas'

/* Gear icons by template, one 16x16 cell each, for bag slots. Reserved art (LICENSE). */

/** The sprite grid with `.` as transparent, so the icon's silhouette reads in the source; every icon fills a 16x16 cell. */
const icon = (text: string): Sprite => {
  const drawn = sprite(text.replaceAll('.', ' '))
  const rows = [...drawn.rows.map((row) => row.padEnd(16, ' ')), ...Array.from({ length: 16 - drawn.height }, () => ' '.repeat(16))]
  return { width: 16, height: 16, rows }
}

const letterOpener = icon(`
.............##.
............#ww#
...........#ww#.
..........#ww#..
.........#ww#...
........#ww#....
.......#ww#.....
......#ww#......
.....####.......
...##ww##.......
..#ww#ww#.......
.#ww#.###.......
#ww#............
#w#.............
##..............
................
`)

const rulerBlade = icon(`
.......##.......
......#ww#......
.....#wwww#.....
.....#wwww#.....
.....#w##w#.....
.....#wwww#.....
.....#w#ww#.....
.....#wwww#.....
.....#w##w#.....
.....#wwww#.....
.....#w#ww#.....
.....#wwww#.....
.....######.....
......#ww#......
......#ww#......
......####......
`)

const cableCutter = icon(`
....##....##....
...#ww#..#ww#...
...#ww#..#ww#...
...#www##www#...
....#wwwwww#....
.....#wwww#.....
......#ww#......
.....##ww##.....
....#ww##ww#....
...#ww#..#ww#...
...#ww#..#ww#...
...#ww#..#ww#...
...#ww#..#ww#...
...#ww#..#ww#...
....##....##....
................
`)

const keyboardMace = icon(`
..############..
.#wwwwwwwwwwww#.
.#w#w#w#w#w#ww#.
.#wwwwwwwwwwww#.
.#w#w#w#w#w#ww#.
.#wwwwwwwwwwww#.
.#ww#######www#.
.#wwwwwwwwwwww#.
..############..
.......##.......
.......##.......
......#ww#......
......#ww#......
......#ww#......
......#ww#......
.......##.......
`)

const ladleOfRuin = icon(`
............###.
...........#ww#.
...........#ww#.
..........#ww#..
..........#ww#..
.........#ww#...
.........#ww#...
........#ww#....
........#ww#....
..######ww#.....
.#wwwwwww#......
.#wwwwwww#......
..#wwwww#.......
...#www#........
....###.........
................
`)

const sporkHalberd = icon(`
....#.#.#.#.....
....#.#.#.#.....
....#w#w#w#.....
....#wwwww#.....
.....#www#......
......#w#.......
......#w#.......
......#w#.......
......#w#.......
......#w#.......
......#w#.......
......#w#.......
......#w#.......
......#w#.......
......#w#.......
.......#........
`)

const cardigan = icon(`
....###..###....
...#www##www#...
..#www#ww#www#..
.#wwww#ww#wwww#.
#wwwww#ww#wwwww#
#w#www#ww#www#w#
#w#www#ww#www#w#
#w#www#ww#www#w#
##.#ww#ww#ww#.##
...#ww#ww#ww#...
...#ww#ww#ww#...
...#ww#w##ww#...
...#ww#ww#ww#...
...#ww#ww#ww#...
...##########...
................
`)

const lanyardMail = icon(`
.....######.....
....#w#..#w#....
...#ww#..#ww#...
..#:::#..#:::#..
.#::::#..#::::#.
#:::::####:::::#
#::::::ww::::::#
#::#::::::::#::#
##.#::::::::#.##
...#::####::#...
...#::#ww#::#...
...#::#ww#::#...
...#::####::#...
...#::::::::#...
...##########...
................
`)

const insulatedCardigan = icon(`
....###..###....
...#www##www#...
..#www#ww#www#..
.#wwww#ww#wwww#.
#w::ww#ww#ww::w#
#wwwww#ww#wwwww#
#w::ww#ww#ww::w#
#wwwww#ww#wwwww#
##.#::#ww#::#.##
...#ww#ww#ww#...
...#::#w##::#...
...#ww#ww#ww#...
...#::#ww#::#...
...#ww#ww#ww#...
...##########...
................
`)

const antiStaticVest = icon(`
....###..###....
...#www##www#...
..#wwww##wwww#..
..#wwwwwwwwww#..
..#wwww##wwww#..
..#www##wwwww#..
..#ww#####www#..
..#wwww##wwww#..
..#www##wwwww#..
..#ww##wwwwww#..
..#wwwwwwwwww#..
..#wwwwwwwwww#..
..#wwwwwwwwww#..
..############..
................
................
`)

const apronOfWarding = icon(`
......####......
.....#w..w#.....
.....#w..w#.....
.....######.....
.....#wwww#.....
.....#wwww#.....
..####wwww####..
.#wwwwwwwwwwww#.
.#wwww####wwww#.
.#www#wwww#www#.
.#www#w##w#www#.
.#wwww#ww#wwww#.
.#wwwww##wwwww#.
.#wwwwwwwwwwww#.
.##############.
................
`)

const ovenMittPlate = icon(`
......######....
.....#wwwwww#...
....#wwwwwwww#..
....#w#####ww#..
....#w#####ww#..
....#wwwwwwww#..
.###wwwwwwwww#..
#www#wwwwwwww#..
#wwww#wwwwwww#..
.#wwwwwwwwwww#..
..#wwwwwwwwww#..
...#wwwwwwww#...
....##########..
....#::::::::#..
....#::::::::#..
....##########..
`)

/** Each gear template's icon. A template without one falls back to its kind's starter piece. */
export const ITEM_ART: Record<string, Sprite> = {
  letter_opener: letterOpener,
  ruler_blade: rulerBlade,
  cable_cutter: cableCutter,
  keyboard_mace: keyboardMace,
  ladle_of_ruin: ladleOfRuin,
  spork_halberd: sporkHalberd,
  cardigan,
  lanyard_mail: lanyardMail,
  insulated_cardigan: insulatedCardigan,
  anti_static_vest: antiStaticVest,
  apron_of_warding: apronOfWarding,
  oven_mitt_plate: ovenMittPlate,
}

export const itemArt = (templateId: string, kind: 'weapon' | 'armor'): Sprite => ITEM_ART[templateId] ?? (kind === 'weapon' ? letterOpener : cardigan)
