/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppLeaderboardRouteImport } from './routes/app/leaderboard'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as HelpTrmnlRouteImport } from './routes/help/trmnl'
import { Route as ConnectTrmnlInstallRouteImport } from './routes/connect/trmnl/install'
import { Route as ConnectTrmnlManageRouteImport } from './routes/connect/trmnl/manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const HelpTrmnlRoute = HelpTrmnlRouteImport.update({
  id: '/help/trmnl',
  path: '/help/trmnl',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectTrmnlInstallRoute = ConnectTrmnlInstallRouteImport.update({
  id: '/connect/trmnl/install',
  path: '/connect/trmnl/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectTrmnlManageRoute = ConnectTrmnlManageRouteImport.update({
  id: '/connect/trmnl/manage',
  path: '/connect/trmnl/manage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/help/trmnl': typeof HelpTrmnlRoute
  '/app/': typeof AppIndexRoute
  '/connect/trmnl/install': typeof ConnectTrmnlInstallRoute
  '/connect/trmnl/manage': typeof ConnectTrmnlManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/help/trmnl': typeof HelpTrmnlRoute
  '/app': typeof AppIndexRoute
  '/connect/trmnl/install': typeof ConnectTrmnlInstallRoute
  '/connect/trmnl/manage': typeof ConnectTrmnlManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/help/trmnl': typeof HelpTrmnlRoute
  '/app/': typeof AppIndexRoute
  '/connect/trmnl/install': typeof ConnectTrmnlInstallRoute
  '/connect/trmnl/manage': typeof ConnectTrmnlManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/privacy'
    | '/support'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/settings'
    | '/help/trmnl'
    | '/app/'
    | '/connect/trmnl/install'
    | '/connect/trmnl/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/support'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/settings'
    | '/help/trmnl'
    | '/app'
    | '/connect/trmnl/install'
    | '/connect/trmnl/manage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/privacy'
    | '/support'
    | '/app/inventory'
    | '/app/leaderboard'
    | '/app/settings'
    | '/help/trmnl'
    | '/app/'
    | '/connect/trmnl/install'
    | '/connect/trmnl/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  HelpTrmnlRoute: typeof HelpTrmnlRoute
  ConnectTrmnlInstallRoute: typeof ConnectTrmnlInstallRoute
  ConnectTrmnlManageRoute: typeof ConnectTrmnlManageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/help/trmnl': {
      id: '/help/trmnl'
      path: '/help/trmnl'
      fullPath: '/help/trmnl'
      preLoaderRoute: typeof HelpTrmnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/trmnl/install': {
      id: '/connect/trmnl/install'
      path: '/connect/trmnl/install'
      fullPath: '/connect/trmnl/install'
      preLoaderRoute: typeof ConnectTrmnlInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect/trmnl/manage': {
      id: '/connect/trmnl/manage'
      path: '/connect/trmnl/manage'
      fullPath: '/connect/trmnl/manage'
      preLoaderRoute: typeof ConnectTrmnlManageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppInventoryRoute: typeof AppInventoryRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInventoryRoute: AppInventoryRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  HelpTrmnlRoute: HelpTrmnlRoute,
  ConnectTrmnlInstallRoute: ConnectTrmnlInstallRoute,
  ConnectTrmnlManageRoute: ConnectTrmnlManageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
